version: "3"
services:
  registry:
    image: verdaccio/verdaccio
    restart: always
    volumes:
      - "./config.yml:/verdaccio/conf/config.yaml"
      - "storage:/verdaccio/storage"
    ports:
      - "4873:4873"


volumes:
  storage: 
